const menu = [
  {
    id: 1,
    title: 'yağlı sütlü krepler',
    category: 'kahvaltı',
    price: 15.99,
    img: './images/item-1.jpeg',
    desc: `Kahvaltılarınızda severek tüketeceğiniz, reçel, marmelat gibi tatlılarla lezzetlendireceğiniz, Pankek nasıl yapılır? sorunuzun cevabını bul Deneyeceklere şimdiden afiyet olsun. :)`,
  },
  {
    id: 2,
    title: 'çift ​​kişilik akşam yemeği',
    category: 'akşam yemeği',
    price: 13.99,
    img: './images/item-2.jpeg',
    desc: `1 litre (5 su bardağı) suyu kaynatın, ardından içerisine 1 tatlı kaşığı tuz ve 1 tatlı kaşığı sıvı yağ atıp iyice karıştırın. Tuz ve yağ iyice karıştıktan sonra 1 paket makarnayı tencereye dökün. Pişirdiğiniz makarnanın kalınlığına göre 10-15 dakika arasında makarnayı kaynatın. İyi yumuşadıktan sonra makarnanın suyunu süzün. `,
  },
  {
    id: 3,
    title: 'milkshake',
    category: 'shakes',
    price: 6.99,
    img: './images/item-3.jpeg',
    desc: `Kakao ve sütü, blender'da güzelce karıştırın,Üzerine şeker, dondurma ve kakaoyu ekleyin ve köpürene kadar karıştırın,Buzları da bardağa alın ve üzerine hazırladığınız milkshake'i doldurun,Dilerseniz üzerine krem şanti de ilave edebilirsiniz, afiyet olsun.`,
  },
  {
    id: 4,
    title: 'country delight',
    category: 'kahvaltı',
    price: 20.99,
    img: './images/item-4.jpeg',
    desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
  },
  {
    id: 5,
    title: 'egg attack',
    category: 'akşam yemeği',
    price: 22.99,
    img: './images/item-5.jpeg',
    desc: `franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up `,
  },
  {
    id: 6,
    title: 'oreo dream',
    category: 'shakes',
    price: 18.99,
    img: './images/item-6.jpeg',
    desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
  },
  {
    id: 7,
    title: 'bacon overflow',
    category: 'kahvaltı',
    price: 8.99,
    img: './images/item-7.jpeg',
    desc: `carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird `,
  },
  {
    id: 8,
    title: 'american classic',
    category: 'akşam yemeği',
    price: 12.99,
    img: './images/item-8.jpeg',
    desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
  },
  {
    id: 9,
    title: 'quarantine buddy',
    category: 'shakes',
    price: 16.99,
    img: './images/item-9.jpeg',
    desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
  },
];
export default menu;
